# Generated by Django 6.0.6 on 2026-07-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardset',
            name='error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='flashcardset',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=16),
        ),
    ]
